### ISSUE TITLE
#1 首页组件命名规范

### ISSUE THREAD

**Issue by yangfch3** [yangfch3/chem2015#1]
组件命名规范：语义化、层级、下划线、多词驼峰命名

eg：`chem_headerWrap_headerContainer_nav_list_right_listItem`

1. 采用层级命名：项目标示符+组件名+子组件名+...

 如上面的例子：`chem`是项目名，`headerWrap`是`header`组件的名字，`headerContainer`是下一级组件的命名，`nav`指代导航条，`list`指代`nav`列表项，`right`指定位置（当有多个列表同时存在的时候）

2. 每部分命名**必须**采用语义化命令，**不能**使用不常用的英文缩写与拼音缩写；可以使用诸如`nav`、`pre`等常用的英文简写，遇到不常用英文单词可采用拼音缩写，但尽量回避；使用常用英文单词用于命名！

3. 多词拼接单词使用驼峰命名法；如`headerWrap`、`headerContainer`、`listItem`等。

4. 命名可采用多`class`的方法，未用于JS DOM操作的标签全部使用`class`来命名，需要DOM操作的添加使用`id`命名，且前面加上`js_`前缀

4. **部分标签命名固定，不可擅自更改**：如用于修复浮动的`div`统一给一个`class`类名：`floatfix`

 因为我们在css中已经写了这样一段代码：
 ```css
 .floatfix {
     *zoom:1}

 .floatfix:after {
     content: "";
     display: table;
     clear: both
 }
 ```

未考虑周全的请补充！
